import { StyleSheet } from "react-native";

const GlobalStyles = StyleSheet.create({
  container: {
    flex: 1,
    paddingHorizontal: 20,
    paddingVertical: 10,
    justifyContent: "center",
    backgroundColor: "#121212",
  },
  cardContainer: {
    flex: 1,
    paddingTop: 25,
    alignItems: "center",
    justifyContent: "flex-start",
    width: "100%",
    backgroundColor: "#1e1e1e",
  },
  timeContainer: {
    backgroundColor: "#333",
    paddingVertical: 5,
    paddingHorizontal: 10,
    borderRadius: 5,
    marginVertical: 5,
    marginTop: 15,
  },
  locationTime: {
    color: "#e0e0e0",
    fontSize: 14,
    fontWeight: "bold",
  },
  ratingContainer: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    marginTop: 5,
    gap: 10,
  },
  ratingText: {
    marginRight: 10,
    color: "#b0b0b0",
    fontSize: 14,
  },
  dropdown: {
    backgroundColor: "#333333",
    padding: 15,
    borderRadius: 7,
    width: "93%",
    marginBottom: 15,
  },
  dropdownContainer: {
    backgroundColor: "#444444",
    borderColor: "#333333",
    borderRadius: 8,
    width: "93%",
    borderColor: "#000",
  },
  redButton: {
    backgroundColor: "#D64933",
    borderBottomWidth: 4,
    borderColor: "#A33B27",
    padding: 10,
    borderRadius: 5,
    alignItems: "center",
  },
  redButtonText: {
    color: "white",
    fontSize: 16,
  },
  badge: {
    backgroundColor: "#D64933",
    paddingVertical: 5,
    paddingHorizontal: 10,
    margin: 20,
    borderRadius: 5,
    position: "absolute",
  },
  badgeText: {
    color: "#fff",
    fontWeight: "bold",
    fontSize: 12,
  },
  resCard: {
    flex: 1,
    backgroundColor: "#1e1e1e",
    borderRadius: 10,
    width: "100%",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.5,
    shadowRadius: 8,
    elevation: 5,
    borderBottomWidth: 4,
    borderColor: "#FF4500",
  },
  resImage: {
    width: "100%",
    height: 150,
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
  },
  resInfo: {
    paddingHorizontal: 15,
    paddingVertical: 10,
  },
  infoContainer: {
    marginTop: 5,
  },
  infoTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#e0e0e0",
  },
  infoDescription: {
    color: "#b0b0b0",
    fontSize: 14,
    marginTop: 5,
  },
  map: { width: "100%", height: "100%" },
  loadingContainer: { flex: 1, justifyContent: "center", alignItems: "center" },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    marginBottom: 20,
    backgroundColor: "#333",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 1,
    alignSelf: "flex-start",
    marginLeft: 10,
  },
  cardWrapper: {
    flex: 1,
    width: "100%",
    paddingHorizontal: 15,
    paddingVertical: 10,
    paddingBottom: 20,
    justifyContent: "center",
    alignItems: "center",
  },
  headline: {
    fontSize: 28,
    fontWeight: "bold",
    textAlign: "start",
    width: "93%",
    marginBottom: 15,
    color: "#e0e0e0",
  },
  containerWaitlist: {
    flex: 1,
    paddingTop: 20,
    backgroundColor: "#121212",
    alignItems: "center",
    justifyContent: "flex-start",
    width: "100%",
  },
  buttonContainer: {
    flexDirection: "row",
    justifyContent: "space-around",
    width: "100%",
    marginBottom: 15,
  },
  cityButton: {
    paddingVertical: 10,
    paddingHorizontal: 20,
    backgroundColor: "#444",
    borderRadius: 5,
  },
  activeCityButton: {
    backgroundColor: "#FF4500",
  },
  button: {
    width: "93%",
    padding: 15,
    borderRadius: 7,
    marginBottom: 15,
    backgroundColor: "#1a1a1a",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#FF4500",
  },
  activeButton: {
    backgroundColor: "#FF4500",
  },
  buttonText: {
    color: "#fff",
    fontSize: 16,
  },
  title: {
    fontSize: 24,
    fontWeight: "bold",
    marginBottom: 20,
    textAlign: "center",
    color: "#e0e0e0",
  },
  input: {
    borderWidth: 1,
    borderColor: "#555",
    borderRadius: 5,
    padding: 12,
    marginBottom: 15,
    width: "100%",
    color: "#e0e0e0",
    backgroundColor: "#222",
  },
  checkboxContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 15,
  },
  label: {
    fontSize: 16,
    fontWeight: "bold",
    marginVertical: 5,
    marginRight: 10,
    textAlign: "left",
    width: 250,
    color: "#e0e0e0",
  },
  cuisineBox: {
    padding: 10,
    borderWidth: 1,
    borderRadius: 5,
    margin: 5,
    backgroundColor: "#2c2c2c",
  },
  selectedCuisine: { color: "#FF4500", fontWeight: "bold" },
  unselectedCuisine: { color: "#e0e0e0" },
  budgetContainer: {
    width: "100%",
    flexDirection: "row",
    justifyContent: "space-between",
    marginVertical: 10,
    gap: 10,
    display: "flex",
    marginBottom: 20,
  },
  budgetButton: {
    padding: 10,
    borderWidth: 1,
    borderColor: "#555",
    borderRadius: 5,
    flex: 1,
    alignItems: "center",
  },
  selectedBudgetButton: {
    backgroundColor: "#FF4500",
    borderColor: "#FF4500",
  },
  budgetText: {
    color: "#fff",
    fontWeight: "bold",
  },
  image: {
    width: "100%",
    height: 200,
    borderRadius: 10,
    marginBottom: 20,
  },
  info: {
    fontSize: 18,
    marginBottom: 10,
    color: "#e0e0e0",
  },
  card: {
    backgroundColor: "#1e1e1e",
    padding: 15,
    borderRadius: 8,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 5,
    marginVertical: 10,
    marginHorizontal: 20,
  },
  creatorText: {
    fontSize: 14,
    fontWeight: "bold",
    color: "#e0e0e0",
    marginBottom: 5,
  },
  reviewText: {
    fontSize: 16,
    color: "#b0b0b0",
    marginBottom: 8,
  },
  ratingText: {
    fontSize: 14,
    color: "#FF4500",
    marginBottom: 5,
  },
  timestampText: {
    fontSize: 12,
    color: "#777",
  },
  imagePreview: {
    width: 100,
    height: 100,
    marginTop: 10,
    borderRadius: 8,
  },
  reviewImage: {
    width: "100%",
    height: 200,
    borderRadius: 8,
    marginTop: 10,
  },
});

export default GlobalStyles;
