import { StyleSheet } from "react-native";

const GlobalStyles = StyleSheet.create({
  container: {
    flex: 1,
    padding: 20,
    justifyContent: "center",
    backgroundColor: "#fff",
  },
  cardContainer: {
    flex: 1,
    paddingTop: 85,
    alignItems: "center",
    justifyContent: "start",
    width: "100%",
    backgroundColor: "#fff",
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#313131",
    justifyContent: "center",
    alignItems: "center",
    position: "absolute",
    top: 60,
    left: 20,
    zIndex: 1,
  },
  cardWrapper: {
    flex: 1,
    width: "100%",
    paddingHorizontal: 15,
    paddingVertical: 10,
    paddingBottom: 20,
    justifyContent: "center",
    alignItems: "center",
  },
  headline: {
    fontSize: 28,
    fontWeight: "bold",
    textAlign: "start",
    width: "93%",
    marginBottom: 15,
  },
  containerWaitlist: {
    flex: 1,
    paddingTop: 20,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "start",
    width: "100%",
  },
  buttonContainer: {
    flexDirection: "row",
    justifyContent: "space-around",
    width: "100%",
    marginBottom: 15,
  },
  cityButton: {
    paddingVertical: 10,
    paddingHorizontal: 20,
    backgroundColor: "#ccc",
    borderRadius: 5,
  },
  activeCityButton: {
    backgroundColor: "#FF4500",
  },
  button: {
    width: "90%",
    padding: 15,
    backgroundColor: "#ccc",
    borderRadius: 5,
    marginBottom: 15,
    alignItems: "center",
  },
  activeButton: {
    backgroundColor: "#FF4500",
  },
  buttonText: {
    color: "#fff",
    fontSize: 16,
  },
  title: {
    fontSize: 24,
    fontWeight: "bold",
    marginBottom: 20,
    textAlign: "center",
    color: "#333",
  },
  input: {
    borderWidth: 1,
    borderColor: "#ccc",
    borderRadius: 5,
    padding: 10,
    marginBottom: 15,
    width: 250,
  },
  checkboxContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 15,
  },
  button: {
    backgroundColor: "#ff4500",
    color: "#fff",
    padding: 10,
    textAlign: "center",
    borderRadius: 5,
    width: 150,
    marginBottom: 15,
  },
  label: {
    fontSize: 16,
    fontWeight: "bold",
    marginVertical: 5,
    marginRight: 10,
    textAlign: "left",
    width: 250,
  },
  cuisineBox: {
    padding: 10,
    borderWidth: 1,
    borderRadius: 5,
    margin: 5,
    backgroundColor: "#f0f0f0",
  },
  selectedCuisine: { color: "#FF4500", fontWeight: "bold" },
  unselectedCuisine: { color: "#333" },
  budgetContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginVertical: 10,
    width: 250,
    gap: 10,
    display: "flex",
  },
  budgetButton: {
    padding: 10,
    borderWidth: 1,
    borderColor: "#ccc",
    borderRadius: 5,
    flex: 1,
  },
  selectedBudgetButton: {
    backgroundColor: "#FF4500",
    borderColor: "#FF4500",
  },
  budgetText: {
    color: "#fff",
    fontWeight: "bold",
  },
  image: {
    width: "100%",
    height: 200,
    borderRadius: 10,
    marginBottom: 20,
  },
  title: {
    fontSize: 24,
    fontWeight: "bold",
    marginBottom: 10,
  },
  info: {
    fontSize: 18,
    marginBottom: 10,
  },
  card: {
    backgroundColor: "#fff",
    padding: 15,
    borderRadius: 8,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 5,
    marginVertical: 10,
    marginHorizontal: 20,
  },
  creatorText: {
    fontSize: 14,
    fontWeight: "bold",
    color: "#333",
    marginBottom: 5,
  },
  reviewText: {
    fontSize: 16,
    color: "#444",
    marginBottom: 8,
  },
  ratingText: {
    fontSize: 14,
    color: "#FF4500",
    marginBottom: 5,
  },
  timestampText: {
    fontSize: 12,
    color: "#777",
  },
  imagePreview: {
    width: 100,
    height: 100,
    marginTop: 10,
    borderRadius: 8,
  },
  reviewImage: {
    width: "100%",
    height: 200,
    borderRadius: 8,
    marginTop: 10,
  },
});

export default GlobalStyles;